# gas-assembler code generated by HrwCC

.section .text
	#debug: func-def: ( int argc , char * * argv ) 
.globl main
.type main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$128, %esp


	#debug: assignment: j = argc ; 
	movl	8(%ebp), %eax
	movl	%eax, -128(%ebp)
	#debug: assignment: array [ 2 ] = i ; 
	pushl	$2
	movl	-124(%ebp), %eax
	popl	%esi
	movl	%eax, -80(%ebp, %esi, 4)
	#debug: assignment: j = idx [ 2 ] ; 
	pushl	$2
	movl	%ebp, %eax
	addl	$-120, %eax
	popl	%esi
	imull	$4, %esi
	addl	%esi, %eax
	movl	(%eax), %eax
	movl	%eax, -128(%ebp)
	#debug: assignment: idx [ 2 ] = j ; 
	pushl	$2
	movl	-128(%ebp), %eax
	popl	%esi
	movl	%eax, -120(%ebp, %esi, 4)
	#debug: return: return 88 ; 
	movl	$88, %eax
	jmp	main_ret


main_ret:
	movl	%ebp, %esp
	popl	%ebp
	ret




# The symbol table 

.section .data
symtab:

