# gas-assembler code generated by HrwCC

.section .text
.globl fac
.type fac, @function
fac:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$0, %esp


	movl	%ebp, %eax
	addl	$8, %eax
	movl	(%eax), %eax
	pushl	%eax
	popl	%ebx
	cmpl	$1, %ebx
	movl	$1, %eax
	jg	fac_reltrue_1
	movl	$0, %eax
fac_reltrue_1:
	testl	%eax, %eax
	jnz	fac_ifbl_0
	jmp	fac_elsebl_0
fac_ifbl_0:
	movl	%ebp, %eax
	addl	$8, %eax
	movl	(%eax), %eax
	pushl	%eax
	subl	$4, %esp
	movl	%ebp, %eax
	addl	$8, %eax
	movl	(%eax), %eax
	pushl	%eax
	popl	%ebx
	subl	$1, %ebx
	pushl	%ebx
	popl	%eax
	movl	%eax, 0(%esp)
	call	fac
	addl	$4, %esp
	popl	%ebx
	imull	%eax, %ebx
	pushl	%ebx
	popl	%eax
	jmp	fac_ret
	jmp	fac_endif_0

fac_elsebl_0:

fac_endif_0:

	movl	$1, %eax
	jmp	fac_ret


fac_ret:
	movl	%ebp, %esp
	popl	%ebp
	ret




.globl main
.type main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$112, %esp


	movl	%ebp, %eax
	addl	$-4, %eax
	pushl	%eax
	popl	%ebx
	movl	$symtab+0, (%ebx)
	subl	$8, %esp
	movl	$symtab+6, 0(%esp)
	subl	$4, %esp
	movl	$25, 0(%esp)
	call	fac
	addl	$4, %esp
	movl	%eax, 4(%esp)
	call	printf
	addl	$8, %esp
	subl	$8, %esp
	movl	$symtab+14, 0(%esp)
	movl	%ebp, %eax
	addl	$-4, %eax
	movl	(%eax), %eax
	movl	%eax, 4(%esp)
	call	printf
	addl	$8, %esp
	movl	%ebp, %eax
	addl	$-112, %eax
	pushl	%eax
	popl	%ebx
	movl	$3, (%ebx)
	movl	%ebp, %eax
	addl	$-108, %eax
	pushl	%eax
	subl	$12, %esp
	movl	%ebp, %eax
	addl	$-54, %eax
	movl	%eax, 0(%esp)
	movl	$symtab+32, 4(%esp)
	movl	%ebp, %eax
	addl	$-112, %eax
	movl	(%eax), %eax
	movl	%eax, 8(%esp)
	call	sprintf
	addl	$12, %esp
	popl	%ebx
	movl	%eax, (%ebx)
	subl	$8, %esp
	movl	$symtab+53, 0(%esp)
	movl	%ebp, %eax
	addl	$-54, %eax
	movl	%eax, 4(%esp)
	call	printf
	addl	$8, %esp
	subl	$12, %esp
	movl	%ebp, %eax
	addl	$-104, %eax
	movl	%eax, 0(%esp)
	movl	%ebp, %eax
	addl	$-54, %eax
	movl	%eax, 4(%esp)
	movl	$50, 8(%esp)
	call	memcpy
	addl	$12, %esp
	subl	$8, %esp
	movl	$symtab+53, 0(%esp)
	movl	%ebp, %eax
	addl	$-104, %eax
	movl	%eax, 4(%esp)
	call	printf
	addl	$8, %esp
	movl	$1, %eax
	jmp	main_ret


main_ret:
	movl	%ebp, %esp
	popl	%ebp
	ret




# The symbol table 

.section .data
symtab:
	.string	"short"
	.string	"fac: %d"
	.string	"this is a %s text"
	.string	"%d is a magic number"
	.string	"[%s]\n"

