# gas-assembler code generated by HrwCC

.section .text
.globl main
.type main, @function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$0, %esp


	subl	$8, %esp
	movl	$symtab+0, 0(%esp)
	movl	%ebp, %eax
	addl	$8, %eax
	movl	(%eax), %eax
	movl	%eax, 4(%esp)
	call	printf
	addl	$8, %esp
	movl	$2, %eax
	jmp	main_ret


main_ret:
	movl	%ebp, %esp
	popl	%ebp
	ret




# The symbol table 

.section .data
symtab:
	.string	"%d arguments:\n"

